#!/bin/bash

if [ -z "$1" ] ; then
    echo "Usage: $0 <ota zip> <json of the build>"
    exit 1
fi

ROM="$1"
OLDJSON="$2"

METADATA=$(unzip -p "$ROM" META-INF/com/android/metadata)
SDK_LEVEL=$(echo "$METADATA" | grep post-sdk-level | cut -f2 -d '=')
TIMESTAMP=$(echo "$METADATA" | grep post-timestamp | cut -f2 -d '=' | cut -f1 -d '-' )

FILENAME=$(basename $ROM)
CODENAME=$(echo $FILENAME | cut -f4 -d '-')
DATE=$(echo $FILENAME | cut -f3 -d '-')
SIZE=$(du -b $ROM | cut -f1 -d '	')

MD5=$(grep md5 "$OLDJSON" | cut -c 12- | sed 's/",//g' )
SHA256=$(grep sha256 "$OLDJSON" | cut -c 15- | sed 's/",//g' )
VERSION=$(grep version "$OLDJSON" | cut -c 16- | sed 's/",//g' )
MAINVERSION=$(echo $VERSION | cut -c 1)

MAINTAINER="Rocky7842"
PAYPAL=""
TELEGRAM=""

if [ "$CODENAME" = "d1x" ] ; then
    PROJECT="crdroid-samsung-note10-5g"
    OEM="Samsung"
    DEVICE="Galaxy Note10 5G"
    BUILDTYPE="Monthly"
    FORUM="https://forum.xda-developers.com/t/4530391/"
    FIRMWARE="https://sourceforge.net/projects/firmware-samsung-note10-5g/files/"
    MODEM=""
    BOOTLOADER=""
    RECOVERY="https://sourceforge.net/projects/$PROJECT/files/crdroid-9/recovery.img/download"
    DEVICETREE="https://github.com/Rocky7842/android_device_samsung_d1x"
    COMMON_DEVICETREE="https://github.com/Rocky7842/android_device_samsung_exynos9820-common"
    KERNEL="https://github.com/Rocky7842/android_kernel_samsung_exynos9820"
elif [ "$CODENAME" = "grus" ] ; then
    PROJECT="crdroid-xiaomi-9-se"
    OEM="Xiaomi"
    DEVICE="Mi 9 SE"
    BUILDTYPE="Monthly"
    FORUM="https://forum.xda-developers.com/t/4533353/"
    FIRMWARE="https://androidfilehost.com/?fid=2981970449027569929"
    MODEM=""
    BOOTLOADER=""
    RECOVERY="https://sourceforge.net/projects/$PROJECT/files/crdroid-9/recovery.img/download"
    DEVICETREE="https://github.com/Rocky7842/android_device_xiaomi_grus"
    COMMON_DEVICETREE=""
    KERNEL="https://github.com/Rocky7842/android_kernel_xiaomi_grus"
elif [ "$CODENAME" = "xmsirius" ] ; then
    PROJECT="crdroid-xiaomi-8-se"
    OEM="Xiaomi"
    DEVICE="Mi 8 SE"
    BUILDTYPE="Monthly"
    FORUM="https://forum.xda-developers.com/t/4535219/"
    FIRMWARE=""
    MODEM=""
    BOOTLOADER=""
    RECOVERY="https://sourceforge.net/projects/$PROJECT/files/crdroid-9/recovery.img/download"
    DEVICETREE="https://github.com/Rocky7842/android_device_xiaomi_xmsirius"
    COMMON_DEVICETREE="https://github.com/Rocky7842/android_device_xiaomi_sdm710-common"
    KERNEL="https://github.com/Rocky7842/android_kernel_xiaomi_sdm710"
fi

DOWNLOAD="https://sourceforge.net/projects/$PROJECT/files/crdroid-$MAINVERSION/$FILENAME/download"
GAPPS="http://downloads.codefi.re/jdcteam/javelinanddart/gapps"

response=$(jq -n --arg maintainer "$MAINTAINER" \
        --arg oem "$OEM" \
        --arg device "$DEVICE" \
        --arg filename "$FILENAME" \
        --arg download "$DOWNLOAD" \
        --arg timestamp "$TIMESTAMP" \
        --arg md5 "$MD5" \
        --arg sha256 "$SHA256" \
        --arg size "$SIZE" \
        --arg version "$VERSION" \
        --arg buildtype "$BUILDTYPE" \
        --arg forum "$FORUM" \
        --arg gapps "$GAPPS" \
        --arg firmware "$FIRMWARE" \
        --arg modem "$MODEM" \
        --arg bootloader "$BOOTLOADER" \
        --arg recovery "$RECOVERY" \
        --arg paypal "$PAYPAL" \
        --arg telegram "$TELEGRAM" \
        --arg dt "$DEVICETREE" \
        --arg common-dt "$COMMON_DEVICETREE" \
        --arg kernel "$KERNEL" \
        '$ARGS.named'
)
wrapped_response=$(jq -n --argjson response "[$response]" '$ARGS.named')
echo "$wrapped_response" > crDroid/$MAINVERSION/$CODENAME.json

git add crDroid/$MAINVERSION/$CODENAME.json
git commit -m "crDroid: $MAINVERSION: $CODENAME: Update autogenerated json to ${DATE}/${TIMESTAMP}"
git push origin main -f

SERVER="rocky7842@frs.sourceforge.net"
echo "login to $SERVER"
rsync -e ssh $ROM $SERVER:/home/frs/project/$PROJECT/crdroid-$MAINVERSION/
